- Tahminlerimin ne kadar doğru olduğuna sayısal olarak bakacağız..

- residual= y - y_pred
- square residual = (residual^2)
- sum square residual = sum((y-y_pred)^2)

- sum square total = sum((y - y_avg)^2)

- R^2(r_square) = 1 - (SSR / SST)
- Eğer R^2 değeri 1'e ne kadar yakın ise o kadar iyi demektir.

<h2>R-Square With Random Forest Regression</h2>

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df=pd.read_csv('/Users/bestecetin/Desktop/machine_learning/courses/machinelearning/Regression/EvaluationRegressionModels/data/random+forest+regression+dataset.csv',sep=";",header=None)

In [3]:
x = df.iloc[:,0].values.reshape(-1,1) #numpya çevirdik ve ,1 koyduk
y = df.iloc[:,1].values.reshape(-1,1)

In [4]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100, random_state = 42 )

In [5]:
rf.fit(x,y)

/var/folders/pc/gs0lq1w52r16_wgx9vm4wxhm0000gn/T/ipykernel_17564/2439990766.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x,y)


RandomForestRegressor(random_state=42)

In [8]:
y_pred = rf.predict(x)

In [9]:
#şimdi predict ettiğimiz değerlerin doğruluğuna bakacağız

In [10]:
from sklearn.metrics import r2_score
print("r_score",r2_score(y,y_pred))

r_score 0.9798724794092587


- burada gerçek y değerimiz (y) ve predict ettiğimiz y değerinin (y_pred) doğruluğuna baktık.

- sonuç 1'e yakın çıktı iyi bir tahmin oldugunu söyleyebiliriz.

In [12]:
y #gerçek y

array([[100],
       [ 80],
       [ 70],
       [ 60],
       [ 50],
       [ 40],
       [ 30],
       [ 20],
       [ 10],
       [  5]])

In [13]:
y_pred #predict y 

array([89.1 , 83.3 , 72.1 , 61.9 , 52.1 , 42.8 , 30.8 , 22.7 , 12.65,
        8.5 ])

<h2>R-Square With Linear Regression</h2>

In [16]:
df=pd.read_csv('/Users/bestecetin/Desktop/machine_learning/courses/machinelearning/Regression/EvaluationRegressionModels/data/linear_regression_dataset.csv',sep=";")

In [19]:
from sklearn.linear_model import LinearRegression
linear_reg= LinearRegression() #modelimi bir variable'a eşitledik

In [20]:
x = df.deneyim.values.reshape(-1,1)
y = df.maas.values.reshape(-1,1)

In [22]:
linear_reg.fit(x,y)
y_pred = linear_reg.predict(x)

In [23]:
from sklearn.metrics import r2_score
print("r_square score:",r2_score(y,y_pred))

r_square score: 0.9775283164949902


In [24]:
y

array([[ 2500],
       [ 2250],
       [ 2750],
       [ 8000],
       [ 9000],
       [ 6900],
       [20000],
       [ 8500],
       [ 6000],
       [ 3500],
       [15000],
       [13000],
       [18000],
       [ 7500]])

In [25]:
y_pred

array([[ 2233.06929596],
       [ 1663.89519747],
       [ 2802.24339445],
       [ 7355.63618235],
       [10770.68077328],
       [ 6217.28798538],
       [18739.11815211],
       [ 9632.3325763 ],
       [ 5078.9397884 ],
       [ 3940.59159143],
       [15324.07356118],
       [13047.37716723],
       [17600.76995513],
       [ 8493.98437933]])